import { useEffect, useState } from "react";
import { roleDataApi } from "../../api/roleData";
import { Send, Users } from "lucide-react";
import { Card, CardHeader } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { useAppData } from "../../data/AppDataContext";
import type { UserRole } from "../../types";

export function CareNetworkPage({ authorName, authorRole }: { authorName: string; authorRole: UserRole; }) {
  const { patient } = useAppData();
  const [connections,setConnections]=useState<any[]>([]); const [selectedPatientId,setSelectedPatientId]=useState<number|"">(""); const [notes,setNotes]=useState<any[]>([]); const [draft,setDraft]=useState(""); const [email,setEmail]=useState(""); const [message,setMessage]=useState("");
  const load=async()=>{try{const data=await roleDataApi.getCareNetwork();setConnections(data.connections);const first=data.connections[0]?.patient?.id;const id=selectedPatientId||first;if(id){setSelectedPatientId(id);const n=await roleDataApi.getNotes(id);setNotes(n.notes);}}catch(e){setMessage(e instanceof Error?e.message:"Unable to load care network.");}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(selectedPatientId)roleDataApi.getNotes(selectedPatientId).then(x=>setNotes(x.notes)).catch(()=>setNotes([]));},[selectedPatientId]);
  const connect=async()=>{if(!email.trim())return;try{const r=await roleDataApi.connect(email.trim());setMessage(r.message||"Connection created.");setEmail("");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to connect account.");}};
  const submit=async()=>{if(!draft.trim())return;try{await roleDataApi.addNote(draft.trim(),selectedPatientId||undefined);setDraft("");setMessage("Note shared with the care team.");if(selectedPatientId){const n=await roleDataApi.getNotes(selectedPatientId);setNotes(n.notes);}}catch(e){setMessage(e instanceof Error?e.message:"Unable to post note.");}};
  const selected=connections.find(c=>c.patient?.id===selectedPatientId)?.patient;
  const displayName=selected?.name||patient.name||"Patient";
  return <div className="space-y-6"><div><h1 className="font-display text-xl font-semibold text-charcoal-900 sm:text-2xl">Care network</h1><p className="mt-1 text-sm text-charcoal-500">Role-based connections and shared care updates stored in PostgreSQL.</p></div>{(authorRole!=="patient"&&connections.length>0)&&<Card><CardHeader title="Connected patients"/><div className="flex flex-wrap gap-2">{connections.filter(c=>c.patient).map(c=><button key={c.patient.id} onClick={()=>setSelectedPatientId(c.patient.id)} className={`rounded-xl border px-3 py-2 text-left ${selectedPatientId===c.patient.id?"border-ink-700 bg-ink-100":"border-paper-300 bg-paper-0"}`}><p className="text-sm font-semibold text-charcoal-900">{c.patient.name}</p><p className="text-[11px] text-charcoal-500">{c.patient.email}</p></button>)}</div></Card>}
  <Card><CardHeader title="Current connections"/><div className="space-y-3">{connections.length===0&&<p className="text-sm text-charcoal-500">No connections yet.</p>}{connections.map((c,i)=><div key={c.patient?.id||i} className="rounded-xl border border-paper-200 p-3"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-ink-800"/><p className="text-sm font-semibold text-charcoal-900">{c.patient?.name||"Patient"}</p></div><div className="mt-2 flex flex-wrap gap-2">{c.caregiver&&<Badge tone="neutral">Caregiver: {c.caregiver.name}</Badge>}{c.physician&&<Badge tone="ink">Physician: {c.physician.name}</Badge>}</div></div>)}</div></Card>
  <Card><CardHeader title="Connect a care team member" subtitle="Use a HealthSync account email to create a role-based connection"/><div className="flex flex-col gap-2 sm:flex-row"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Account email" className="min-w-0 flex-1 rounded-xl border border-paper-300 bg-paper-50 px-3 py-2.5 text-sm outline-none focus:border-ink-700"/><button onClick={connect} className="rounded-xl bg-ink-800 px-4 py-2.5 text-xs font-semibold text-white">Connect</button></div>{message&&<p className="mt-2 text-xs text-charcoal-500">{message}</p>}</Card>
  <Card><CardHeader title={`Shared notes · ${displayName}`}/><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={3} placeholder="Share an observation, question, or update..." className="w-full resize-none rounded-xl border border-paper-200 bg-paper-50 p-3 text-sm text-charcoal-900 focus:border-ink-700 focus:outline-none"/><div className="mt-3 flex justify-end"><button onClick={submit} disabled={authorRole!=="patient"&&!selectedPatientId} className="flex items-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50"><Send className="h-3.5 w-3.5"/>Post note</button></div><div className="mt-5 space-y-3">{notes.length===0&&<p className="text-sm text-charcoal-500">No notes for this patient yet.</p>}{notes.map(n=><div key={n.id} className="rounded-xl border border-paper-200 bg-paper-50 p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-charcoal-900">{n.author}</p><span className="text-xs text-charcoal-500">{new Date(n.timestamp).toLocaleString()}</span></div><Badge tone={n.authorRole==="doctor"?"ink":"neutral"}>{n.authorRole}</Badge><p className="mt-2 text-sm leading-relaxed text-charcoal-700">{n.note}</p></div>)}</div></Card></div>;
}
