import { useEffect, useState } from "react";
import { AlertTriangle, PhoneCall, ShieldCheck } from "lucide-react";
import { Card } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { roleDataApi, type EmergencyRecord } from "../../api/roleData";

export function DoctorEmergencies() {
  const [items,setItems]=useState<EmergencyRecord[]>([]); const [error,setError]=useState("");
  const load=()=>roleDataApi.getEmergencies().then(x=>setItems(x.emergencies)).catch(e=>setError(e instanceof Error?e.message:"Unable to load emergency history."));
  useEffect(()=>{void load();},[]);
  const active=items.filter(x=>x.active);
  const resolve=async(id:number)=>{ try { await fetch(`${import.meta.env.VITE_API_URL||"http://localhost:5000/api"}/sos`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("healthsync_token")||""}`},body:JSON.stringify({active:false,alertId:id})}); await load(); } catch(e){setError(e instanceof Error?e.message:"Unable to resolve emergency.");} };
  return <div className="space-y-6"><div><h1 className="font-display text-xl font-semibold text-charcoal-900 sm:text-2xl">Emergency log</h1><p className="mt-1 text-sm text-charcoal-500">SOS triggers from all patients connected to your physician account.</p></div>{error&&<Card><p className="text-sm text-brick-700">{error}</p></Card>}{active.map(item=><Card key={item.id} className="border-brick-600/30 bg-brick-100/40"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-brick-600 text-white"><AlertTriangle className="h-5 w-5"/></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-brick-700">Active SOS — {item.patientName}</p><Badge tone="brick">Unresolved</Badge></div><p className="mt-1 text-sm text-charcoal-700">{item.message}</p><div className="mt-3 flex flex-wrap gap-2"><button className="flex items-center gap-1.5 rounded-lg bg-ink-800 px-3.5 py-2 text-xs font-semibold text-white"><PhoneCall className="h-3.5 w-3.5"/>Call patient</button><button onClick={()=>resolve(item.id)} className="flex items-center gap-1.5 rounded-lg border border-sage-600/40 bg-sage-100 px-3.5 py-2 text-xs font-semibold text-sage-700"><ShieldCheck className="h-3.5 w-3.5"/>Mark resolved</button></div></div></div></Card>)}{!active.length&&<Card><div className="flex flex-col items-center py-8 text-center"><ShieldCheck className="h-6 w-6 text-sage-700"/><p className="mt-3 text-sm font-medium text-charcoal-900">No active emergencies</p><p className="mt-1 max-w-sm text-xs text-charcoal-500">Connected patient SOS events will appear here.</p></div></Card>}<Card><p className="mb-3 font-semibold text-charcoal-900">Recent history</p><div className="space-y-2.5">{items.map(item=><div key={item.id} className="flex items-center justify-between rounded-lg border border-paper-200 px-3.5 py-2.5"><div><p className="text-sm font-medium text-charcoal-900">{item.patientName} — SOS</p><p className="text-xs text-charcoal-500">{new Date(item.createdAt).toLocaleString()}</p></div><Badge tone={item.active?"brick":"sage"}>{item.active?"Unresolved":"Resolved"}</Badge></div>)}</div></Card></div>;
}
