import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CalendarPlus, Download, Plus, Stethoscope } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Card, CardHeader } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { AdherenceRing } from "../../components/ui/AdherenceRing";
import { roleDataApi, type PatientBundle } from "../../api/roleData";
export function DoctorPatientDetail(){
 const {id}=useParams();const nav=useNavigate();const[bundle,setBundle]=useState<PatientBundle|null>(null);const[note,setNote]=useState("");const[med,setMed]=useState({name:"",dosage:"",schedule:"",stock:"0"});const[appt,setAppt]=useState({title:"Follow-up consultation",date:"",time:""});const[message,setMessage]=useState("");
 const load=()=>id?roleDataApi.getPatient("doctor",id).then(setBundle).catch(e=>setMessage(e.message)):undefined;useEffect(()=>{void load();},[id]);
 const submitNote=async(e:FormEvent)=>{e.preventDefault();if(!note.trim()||!id)return;try{const r=await fetch(`${import.meta.env.VITE_API_URL||"http://localhost:5000/api"}/doctor/patients/${id}/clinical-note`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("healthsync_token")||""}`},body:JSON.stringify({note})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||"Unable to save clinical update.");setNote("");setMessage("Clinical update saved and shared with the patient/care team.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save clinical update.");}};
 const addMed=async(e:FormEvent)=>{e.preventDefault();if(!id)return;try{const r=await fetch(`${import.meta.env.VITE_API_URL||"http://localhost:5000/api"}/doctor/patients/${id}/medications`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("healthsync_token")||""}`},body:JSON.stringify({...med,stock:Number(med.stock)})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||"Unable to add medication.");setMed({name:"",dosage:"",schedule:"",stock:"0"});await load();setMessage("Medication instruction added to the patient record.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to add medication.");}};
 const schedule=async(e:FormEvent)=>{e.preventDefault();if(!id||!appt.date||!appt.time)return;try{const r=await roleDataApi.scheduleForPatient(id,appt);setMessage("Follow-up appointment scheduled and the patient was notified.");setAppt({title:"Follow-up consultation",date:"",time:""});await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to schedule appointment.");}};
 if(!bundle)return <div className="space-y-4"><button onClick={()=>nav("/doctor")} className="flex items-center gap-1.5 text-xs text-charcoal-500"><ArrowLeft className="h-3.5 w-3.5"/>Back</button><Card><p className="text-sm text-charcoal-500">{message||"Loading patient record…"}</p></Card></div>;
 const p=bundle.patient;
 return <div className="space-y-6"><button onClick={()=>nav("/doctor")} className="flex items-center gap-1.5 text-xs font-medium text-charcoal-500 hover:text-ink-800"><ArrowLeft className="h-3.5 w-3.5"/>Back to patients</button><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-display text-xl font-semibold text-charcoal-900 sm:text-2xl">{p.name}</h1><p className="mt-1 text-sm text-charcoal-500">{p.patientCode} · Caregiver: {p.primaryCaregiver}</p></div><button className="flex items-center gap-2 rounded-lg border border-paper-300 px-3.5 py-2 text-xs font-semibold"><Download className="h-3.5 w-3.5"/>Export FHIR record</button></div>{message&&<div className="rounded-xl border border-ink-700/30 bg-ink-100 px-4 py-3 text-xs text-ink-800">{message}</div>}
 <Card><CardHeader title="Connected care team" subtitle="The physician and caregiver share authorized updates around this patient."/><div className="flex flex-wrap gap-2">{(bundle.careTeam||[]).map(m=><Badge key={m.id} tone={m.role==='doctor'?"ink":"neutral"}>{m.role}: {m.name}</Badge>)}{!(bundle.careTeam||[]).length&&<p className="text-sm text-charcoal-500">No other care-team member is connected yet.</p>}</div></Card>
 <div className="grid gap-6 lg:grid-cols-3"><Card className="flex items-center justify-center"><AdherenceRing percent={bundle.adherenceRate}/></Card><Card className="lg:col-span-2"><CardHeader title="Current medications"/><div className="space-y-2.5">{bundle.medications.length?bundle.medications.map((m:any)=><div key={m.id} className="flex items-center justify-between rounded-lg border border-paper-200 px-3.5 py-2.5"><div><p className="text-sm font-medium text-charcoal-900">{m.name} <span className="text-xs font-normal text-charcoal-500">{m.dosage}</span></p><p className="text-xs text-charcoal-500">{m.schedule}</p></div><Badge tone={m.stock<=6?"brick":"sage"}>{m.stock} in stock</Badge></div>):<p className="text-sm text-charcoal-500">No medications recorded.</p>}</div></Card></div>
 <div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader title="Clinical update" subtitle="Add a note for the shared patient record"/><form onSubmit={submitNote} className="space-y-3"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Assessment, follow-up instruction, observation…" className="w-full rounded-xl border border-paper-300 p-3 text-sm outline-none focus:border-ink-700"/><button className="flex items-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white"><Stethoscope className="h-3.5 w-3.5"/>Save clinical update</button></form></Card><Card><CardHeader title="Schedule follow-up"/><form onSubmit={schedule} className="space-y-3"><input value={appt.title} onChange={e=>setAppt({...appt,title:e.target.value})} placeholder="Appointment title" className="w-full rounded-xl border border-paper-300 p-2.5 text-sm"/><input type="date" value={appt.date} onChange={e=>setAppt({...appt,date:e.target.value})} className="w-full rounded-xl border border-paper-300 p-2.5 text-sm"/><input type="time" value={appt.time} onChange={e=>setAppt({...appt,time:e.target.value})} className="w-full rounded-xl border border-paper-300 p-2.5 text-sm"/><button className="flex w-full items-center justify-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white"><CalendarPlus className="h-3.5 w-3.5"/>Schedule for patient</button></form></Card></div>
 <Card><CardHeader title="Add medication" subtitle="Add a medication instruction for this patient"/><form onSubmit={addMed} className="grid gap-3 sm:grid-cols-4"><input value={med.name} onChange={e=>setMed({...med,name:e.target.value})} placeholder="Medicine" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><input value={med.dosage} onChange={e=>setMed({...med,dosage:e.target.value})} placeholder="Dosage" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><input value={med.schedule} onChange={e=>setMed({...med,schedule:e.target.value})} placeholder="Schedule" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><input value={med.stock} onChange={e=>setMed({...med,stock:e.target.value})} placeholder="Stock" type="number" min="0" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><button className="sm:col-span-4 flex items-center justify-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5"/>Add medication instruction</button></form></Card>
 </div>;
}
