import { useEffect, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, HeartPulse, Pill, ShieldCheck, Stethoscope, Users2 } from "lucide-react";
import { Link } from "react-router-dom";
import { Card } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { EmergencyDialog } from "../../components/emergency/EmergencyDialog";
import { roleDataApi, type EmergencyRecord } from "../../api/roleData";

function duration(item:EmergencyRecord){if(!item.resolvedAt)return null;const minutes=Math.max(1,Math.round((new Date(item.resolvedAt).getTime()-new Date(item.createdAt).getTime())/60000));return minutes<60?`${minutes} min`:`${Math.floor(minutes/60)}h ${minutes%60}m`;}

export function DoctorEmergencies(){
 const [items,setItems]=useState<EmergencyRecord[]>([]),[feedback,setFeedback]=useState(""),[dialog,setDialog]=useState<{kind:"claim"|"resolve";item:EmergencyRecord}|null>(null),[busy,setBusy]=useState(false),[resolutionNote,setResolutionNote]=useState("");
 const stored=localStorage.getItem("healthsync_user");let physicianId=0;try{physicianId=Number(stored?JSON.parse(stored).id:0);}catch{physicianId=0;}
 const load=()=>roleDataApi.getEmergencies().then(x=>setItems(x.emergencies)).catch(e=>setFeedback(e instanceof Error?e.message:"Unable to load emergency history."));
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("healthsync:realtime",refresh);return()=>window.removeEventListener("healthsync:realtime",refresh);},[]);
 const closeDialog=()=>{if(!busy){setDialog(null);setResolutionNote("");}};
 const confirmAction=async()=>{if(!dialog)return;setBusy(true);setFeedback("");try{if(dialog.kind==="claim"){await roleDataApi.claimEmergency(dialog.item.id);setFeedback("You are now responding to this emergency.");}else{await roleDataApi.resolveEmergency(dialog.item.id,resolutionNote);setFeedback("Emergency resolved.");}setDialog(null);setResolutionNote("");await load();}catch(error){const message=error instanceof Error?error.message:"Unable to update this emergency.";setFeedback(message.toLowerCase().includes("already")?"Another physician has already responded to this emergency.":message);setDialog(null);setResolutionNote("");await load();}finally{setBusy(false);}};
 const active=items.filter(item=>item.active),history=items.filter(item=>!item.active);
 return <div className="doctor-emergencies space-y-6">
  <div><h1 className="font-display text-xl font-semibold text-charcoal-900 sm:text-2xl">Emergency response</h1><p className="mt-1 text-sm text-charcoal-500">System-wide unresolved SOS queue. Claiming an event grants temporary patient-record access until resolution.</p></div>
  {feedback&&<div className={`doctor-emergency-feedback ${feedback.includes("resolved")||feedback.includes("responding")?"is-success":"is-error"}`} role="status">{feedback}</div>}
  <div className="doctor-emergency-list">
   {active.map(item=>{const mine=item.respondingPhysician?.id===physicianId;return <article key={item.id} className={`doctor-emergency-card is-${item.status.toLowerCase()}`}>
    <div className="doctor-emergency-card__top"><Badge tone={item.status==="ACTIVE"?"brick":"gold"}>{item.status==="ACTIVE"?"Active emergency":"Physician responding"}</Badge><time>Triggered {new Date(item.createdAt).toLocaleString()}</time></div>
    <div className="doctor-emergency-card__identity"><span><AlertTriangle/></span><div><small>Patient</small><h2>{item.patientName}</h2><p>Triggered by {item.triggeredBy.name} · {item.triggeredBy.role}</p></div></div>
    <div className="doctor-emergency-snapshot">
     <section><h3><HeartPulse/>Latest vitals</h3><dl><div><dt>BP</dt><dd>{item.latestVital?.systolic&&item.latestVital?.diastolic?`${item.latestVital.systolic}/${item.latestVital.diastolic}`:"Not recorded"}</dd></div><div><dt>Heart rate</dt><dd>{item.latestVital?.heartRate?`${item.latestVital.heartRate} bpm`:"Not recorded"}</dd></div>{item.latestVital?.glucose!=null&&<div><dt>Glucose</dt><dd>{item.latestVital.glucose} mg/dL</dd></div>}</dl></section>
     <section><h3><Pill/>Medication</h3>{item.medications.length?<ul>{item.medications.slice(0,3).map((medication,index)=><li key={`${medication.name}-${index}`}><strong>{medication.name}</strong><span>{medication.dosage}</span></li>)}</ul>:<p>Not recorded</p>}</section>
     <section><h3><Activity/>Clinical context</h3>{item.latestClinicalRecord?<><strong>{item.latestClinicalRecord.title}</strong><p>{item.latestClinicalRecord.status.replaceAll("_"," ")} · {new Date(item.latestClinicalRecord.clinicalDate).toLocaleDateString()}</p></>:<p>No recent clinical context</p>}</section>
     <section><h3><Users2/>Care team</h3>{item.careTeam.length?<ul>{item.careTeam.map(member=><li key={member.id}><strong>{member.role}</strong><span>{member.name}</span></li>)}</ul>:<p>No connected care team</p>}</section>
    </div>
    <div className="doctor-emergency-card__footer"><div>{item.respondingPhysician?<><small>{mine?"You are responding":"Being handled by"}</small><strong>{item.respondingPhysician.name}</strong>{item.acknowledgedAt&&<span>Responded {new Date(item.acknowledgedAt).toLocaleString()}</span>}</>:<span>Awaiting a physician response</span>}</div><div className="doctor-emergency-card__actions">{item.status==="ACTIVE"&&<button onClick={()=>setDialog({kind:"claim",item})} className="is-respond"><Stethoscope/>Respond to Emergency</button>}{mine&&<><Link to={`/doctor/patients/${item.patientId}`}>View Patient</Link><button onClick={()=>setDialog({kind:"resolve",item})} className="is-resolve"><ShieldCheck/>Resolve Emergency</button></>}</div></div>
   </article>;})}
  </div>
  {!active.length&&<Card><div className="flex flex-col items-center py-8 text-center"><ShieldCheck className="h-6 w-6 text-sage-700"/><p className="mt-3 text-sm font-medium text-charcoal-900">No active emergencies</p><p className="mt-1 max-w-sm text-xs text-charcoal-500">New patient or caregiver-triggered SOS events will appear here.</p></div></Card>}
  <Card className="doctor-emergency-history"><div className="doctor-emergency-history__heading"><div><p>Emergency archive</p><h2>Recent history</h2></div><span>{history.length} resolved</span></div><div className="doctor-emergency-history__list">{history.map(item=><article key={item.id}><span><CheckCircle2/></span><div><strong>{item.patientName}</strong><p>Triggered by {item.triggeredBy.name} · {new Date(item.createdAt).toLocaleString()}</p>{item.resolutionNote&&<blockquote>{item.resolutionNote}</blockquote>}</div><dl><div><dt>Responded by</dt><dd>{item.respondingPhysician?.name||"Not recorded"}</dd></div><div><dt>Resolved</dt><dd>{item.resolvedAt?new Date(item.resolvedAt).toLocaleString():"Not recorded"}</dd></div>{duration(item)&&<div><dt>Duration</dt><dd>{duration(item)}</dd></div>}</dl><Badge tone="sage">Resolved</Badge></article>)}{!history.length&&<p className="doctor-emergency-history__empty">No resolved emergencies recorded.</p>}</div></Card>
  <EmergencyDialog open={dialog?.kind==="claim"} eyebrow="Temporary clinical access" title="Respond to Emergency?" description={<>You will become the responding physician for <strong>{dialog?.item.patientName}</strong> and receive temporary access to relevant patient records until this emergency is resolved.</>} note="Other physicians will see that you are handling this emergency." confirmLabel="Respond to Emergency" busyLabel="Responding…" busy={busy} onClose={closeDialog} onConfirm={()=>void confirmAction()}/>
  <EmergencyDialog open={dialog?.kind==="resolve"} eyebrow="Complete response" title="Resolve Emergency" tone="clinical" description={<>Mark the emergency for <strong>{dialog?.item.patientName}</strong> as resolved. Temporary emergency access will end unless you are already part of the patient's Care Network.</>} confirmLabel="Resolve Emergency" busyLabel="Resolving…" busy={busy} onClose={closeDialog} onConfirm={()=>void confirmAction()}><div className="emergency-dialog__field"><label htmlFor="resolution-note">Resolution note <span>(optional)</span></label><textarea id="resolution-note" value={resolutionNote} maxLength={2000} onChange={event=>setResolutionNote(event.target.value)} placeholder="Add a brief resolution note (optional)"/></div></EmergencyDialog>
 </div>;
}
