import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, HeartPulse, Send, XCircle } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Card, CardHeader } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { AdherenceRing } from "../../components/ui/AdherenceRing";
import { roleDataApi, type PatientBundle } from "../../api/roleData";

export function CaregiverPatientDetail() {
  const { id } = useParams(); const nav = useNavigate();
  const [bundle,setBundle]=useState<PatientBundle|null>(null); const [note,setNote]=useState(""); const [message,setMessage]=useState("");
  const [vitals,setVitals]=useState({heartRate:"",systolic:"",diastolic:"",glucose:""});
  const load=async()=>{if(!id)return;try{setBundle(await roleDataApi.getPatient("caregiver",id));}catch(e){setMessage(e instanceof Error?e.message:"Unable to load patient.");}};
  useEffect(()=>{void load();},[id]);
  const submitObservation=async(e:FormEvent)=>{e.preventDefault();if(!note.trim()||!id)return;try{const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";const r=await fetch(`${API}/caregiver/patients/${id}/observation`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("healthsync_token")||""}`},body:JSON.stringify({note:note.trim()})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||"Unable to save observation.");setNote("");setMessage("Observation shared with the care team.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save observation.");}};
  const logMedication=async(medicationId:number,status:"TAKEN"|"MISSED")=>{try{await roleDataApi.logMedication(id!,medicationId,status);setMessage(status==="TAKEN"?"Dose marked taken and shared with the care team.":"Dose marked missed and an alert was created.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to update medication status.");}};
  const addVital=async(e:FormEvent)=>{e.preventDefault();try{await roleDataApi.addPatientVital(id!,vitals);setVitals({heartRate:"",systolic:"",diastolic:"",glucose:""});setMessage("Vital reading added to the patient's record.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save vital reading.");}};
  if(!bundle)return <div className="space-y-4"><button onClick={()=>nav("/caregiver/patients")} className="flex items-center gap-1.5 text-xs font-medium text-charcoal-500"><ArrowLeft className="h-3.5 w-3.5"/>Back to patients</button><Card><p className="text-sm text-charcoal-500">{message||"Loading patient record…"}</p></Card></div>;
  const p=bundle.patient;
  return <div className="caregiver-patient-detail space-y-6">
    <button onClick={()=>nav("/caregiver/patients")} className="flex items-center gap-1.5 text-xs font-medium text-charcoal-500 hover:text-ink-800"><ArrowLeft className="h-3.5 w-3.5"/>Back to patients</button>
    <div><h1 className="font-display text-xl font-semibold text-charcoal-900 sm:text-2xl">{p.name}</h1><p className="mt-1 text-sm text-charcoal-500">{p.patientCode} · Connected patient</p></div>
    {message&&<div className="rounded-xl border border-ink-700/30 bg-ink-100 px-4 py-3 text-xs text-ink-800">{message}</div>}
    <Card><CardHeader title="Care team" subtitle="Everyone shown here is connected to this patient through PostgreSQL and is visible only to authorized care-team members."/><div className="flex flex-wrap gap-2">{(bundle.careTeam||[]).map(m=><Badge key={m.id} tone={m.role==='doctor'?"ink":"neutral"}>{m.role}: {m.name}</Badge>)}{!(bundle.careTeam||[]).length&&<p className="text-sm text-charcoal-500">No other care-team member is connected yet.</p>}</div></Card>
    <div className="grid gap-6 lg:grid-cols-3"><Card className="flex flex-col items-center justify-center"><AdherenceRing percent={bundle.adherenceRate}/><p className="mt-3 text-xs text-charcoal-500">Medication adherence</p></Card><Card className="lg:col-span-2"><CardHeader title="Current medications" subtitle="Monitor and record the day-to-day medication status."/><div className="space-y-2.5">{bundle.medications.length?bundle.medications.map((m:any)=>{const last=m.logs?.[0];return <div key={m.id} className="rounded-lg border border-paper-200 px-3.5 py-3"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-charcoal-900">{m.name} <span className="text-xs font-normal text-charcoal-500">{m.dosage}</span></p><p className="text-xs text-charcoal-500">{m.schedule} · {m.stock} in stock</p></div><Badge tone={last?.status==='TAKEN'?"sage":last?.status==='MISSED'?"brick":"neutral"}>{last?.status||"PENDING"}</Badge></div><div className="mt-2 flex gap-2"><button onClick={()=>void logMedication(m.id,"TAKEN")} className="flex items-center gap-1 rounded-lg border border-sage-600/30 bg-sage-100 px-3 py-1.5 text-[11px] font-semibold text-sage-700"><CheckCircle2 className="h-3.5 w-3.5"/>Taken</button><button onClick={()=>void logMedication(m.id,"MISSED")} className="flex items-center gap-1 rounded-lg border border-brick-600/30 bg-brick-100 px-3 py-1.5 text-[11px] font-semibold text-brick-700"><XCircle className="h-3.5 w-3.5"/>Missed</button></div></div>}) : <p className="text-sm text-charcoal-500">No medications recorded.</p>}</div></Card></div>
    <Card><CardHeader title="Record a vital" subtitle="Caregivers can add home/observed readings to the patient's record."/><form onSubmit={addVital} className="grid gap-3 sm:grid-cols-4"><input value={vitals.heartRate} onChange={e=>setVitals({...vitals,heartRate:e.target.value})} placeholder="Heart rate" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><input value={vitals.systolic} onChange={e=>setVitals({...vitals,systolic:e.target.value})} placeholder="Systolic" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><input value={vitals.diastolic} onChange={e=>setVitals({...vitals,diastolic:e.target.value})} placeholder="Diastolic" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><input value={vitals.glucose} onChange={e=>setVitals({...vitals,glucose:e.target.value})} placeholder="Glucose" className="rounded-xl border border-paper-300 p-2.5 text-sm"/><button className="sm:col-span-4 flex items-center justify-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white"><HeartPulse className="h-3.5 w-3.5"/>Save vital reading</button></form></Card>
    <Card><CardHeader title="Recent vitals" subtitle="Latest health readings available for this connected patient"/><div className="grid gap-2 sm:grid-cols-2">{bundle.vitals.length?bundle.vitals.slice(0,8).map((v:any)=><div key={v.id} className="rounded-lg border border-paper-200 p-3 text-xs"><p className="font-semibold text-charcoal-900">{new Date(v.recordedAt).toLocaleString()}</p><p className="mt-1 text-charcoal-600">HR {v.heartRate??"—"} · BP {v.systolic??"—"}/{v.diastolic??"—"} · Glucose {v.glucose??"—"}</p></div>):<p className="text-sm text-charcoal-500">No vitals recorded.</p>}</div></Card>
    <Card><CardHeader title="Care observation" subtitle="Record something you observed while supporting this patient."/><form onSubmit={submitObservation} className="space-y-3"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Example: Patient felt dizzy after breakfast…" className="w-full rounded-xl border border-paper-300 p-3 text-sm outline-none focus:border-ink-700"/><button className="flex items-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white"><Send className="h-3.5 w-3.5"/>Share observation</button></form></Card>
  </div>;
}
