import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, Send, XCircle } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Card, CardHeader } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { AdherenceRing } from "../../components/ui/AdherenceRing";
import { ClinicalRecordList } from "../../components/clinical/ClinicalRecordList";
import { roleDataApi, type PatientBundle } from "../../api/roleData";
import { vitalApi, type VitalInput, type VitalRecord } from "../../api/vitalApi";
import { VitalEntryForm, VitalHistory, VitalSummary, VitalTrends } from "../../components/vitals/VitalMonitoring";
import { EmergencyDialog } from "../../components/emergency/EmergencyDialog";

export function CaregiverPatientDetail() {
  const { id } = useParams(); const nav = useNavigate();
  const [bundle,setBundle]=useState<PatientBundle|null>(null); const [note,setNote]=useState(""); const [message,setMessage]=useState("");
  const [savingVital,setSavingVital]=useState(false);
  const [emergencyDialogOpen,setEmergencyDialogOpen]=useState(false);const [sendingEmergency,setSendingEmergency]=useState(false);
  const load=async()=>{if(!id)return;try{setBundle(await roleDataApi.getPatient("caregiver",id));}catch(e){setMessage(e instanceof Error?e.message:"Unable to load patient.");}};
  useEffect(()=>{void load();},[id]);
  const submitObservation=async(e:FormEvent)=>{e.preventDefault();if(!note.trim()||!id)return;try{const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";const r=await fetch(`${API}/caregiver/patients/${id}/observation`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("healthsync_token")||""}`},body:JSON.stringify({note:note.trim()})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||"Unable to save observation.");setNote("");setMessage("Observation shared with the care team.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save observation.");}};
  const logMedication=async(medicationId:number,status:"TAKEN"|"MISSED")=>{try{await roleDataApi.logMedication(id!,medicationId,status);setMessage(status==="TAKEN"?"Dose marked taken and shared with the care team.":"Dose marked missed and an alert was created.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to update medication status.");}};
  const addVital=async(input:VitalInput)=>{setSavingVital(true);try{await vitalApi.createForPatient("caregiver",id!,input);setMessage("Vital reading added with caregiver provenance.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save vital reading.");throw e;}finally{setSavingVital(false);}};
  const triggerEmergency=async()=>{if(!id)return;setSendingEmergency(true);try{await roleDataApi.triggerEmergency(id);setMessage("Emergency SOS sent.");setEmergencyDialogOpen(false);}catch(e){setMessage(e instanceof Error?e.message:"Unable to send the emergency alert. Please try again.");setEmergencyDialogOpen(false);}finally{setSendingEmergency(false);}};
  if(!bundle)return <div className="space-y-4"><button onClick={()=>nav("/caregiver/patients")} className="flex items-center gap-1.5 text-xs font-medium text-charcoal-500"><ArrowLeft className="h-3.5 w-3.5"/>Back to patients</button><Card><p className="text-sm text-charcoal-500">{message||"Loading patient record…"}</p></Card></div>;
  const p=bundle.patient;
  return <div className="caregiver-patient-detail space-y-6">
    <button onClick={()=>nav("/caregiver/patients")} className="flex items-center gap-1.5 text-xs font-medium text-charcoal-500 hover:text-ink-800"><ArrowLeft className="h-3.5 w-3.5"/>Back to patients</button>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-xl font-semibold text-charcoal-900 sm:text-2xl">{p.name}</h1><p className="mt-1 text-sm text-charcoal-500">{p.patientCode} · Connected patient</p></div><button onClick={()=>setEmergencyDialogOpen(true)} className="caregiver-trigger-emergency"><AlertTriangle/>Trigger emergency</button></div>
    {message&&<div className="rounded-xl border border-ink-700/30 bg-ink-100 px-4 py-3 text-xs text-ink-800">{message}</div>}
    <Card><CardHeader title="Care team" subtitle="Everyone shown here is connected to this patient through PostgreSQL and is visible only to authorized care-team members."/><div className="flex flex-wrap gap-2">{(bundle.careTeam||[]).map(m=><Badge key={m.id} tone={m.role==='doctor'?"ink":"neutral"}>{m.role}: {m.name}</Badge>)}{!(bundle.careTeam||[]).length&&<p className="text-sm text-charcoal-500">No other care-team member is connected yet.</p>}</div></Card>
    <div className="grid gap-6 lg:grid-cols-3"><Card className="flex flex-col items-center justify-center"><AdherenceRing percent={bundle.adherenceRate}/><p className="mt-3 text-xs text-charcoal-500">Medication adherence</p></Card><Card className="lg:col-span-2"><CardHeader title="Current medications" subtitle="Monitor and record the day-to-day medication status."/><div className="space-y-2.5">{bundle.medications.length?bundle.medications.map((m:any)=>{const last=m.logs?.[0];return <div key={m.id} className="rounded-lg border border-paper-200 px-3.5 py-3"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-charcoal-900">{m.name} <span className="text-xs font-normal text-charcoal-500">{m.dosage}</span></p><p className="text-xs text-charcoal-500">{m.schedule} · {m.stock} in stock</p></div><Badge tone={last?.status==='TAKEN'?"sage":last?.status==='MISSED'?"brick":"neutral"}>{last?.status||"PENDING"}</Badge></div><div className="mt-2 flex gap-2"><button onClick={()=>void logMedication(m.id,"TAKEN")} className="flex items-center gap-1 rounded-lg border border-sage-600/30 bg-sage-100 px-3 py-1.5 text-[11px] font-semibold text-sage-700"><CheckCircle2 className="h-3.5 w-3.5"/>Taken</button><button onClick={()=>void logMedication(m.id,"MISSED")} className="flex items-center gap-1 rounded-lg border border-brick-600/30 bg-brick-100 px-3 py-1.5 text-[11px] font-semibold text-brick-700"><XCircle className="h-3.5 w-3.5"/>Missed</button></div></div>}) : <p className="text-sm text-charcoal-500">No medications recorded.</p>}</div></Card></div>
    <Card><CardHeader title="Vitals & monitoring" subtitle="Append a home/observed reading or review the patient's longitudinal history."/><VitalSummary vitals={bundle.vitals as VitalRecord[]}/><div className="mt-4"><VitalEntryForm onSubmit={addVital} busy={savingVital}/></div><div className="mt-4"><VitalTrends vitals={bundle.vitals as VitalRecord[]}/></div><div className="mt-4"><VitalHistory vitals={bundle.vitals as VitalRecord[]} limit={8}/></div></Card>
    <Card><CardHeader title="Clinical records" subtitle="Read-only physician-authored history for this connected patient."/><ClinicalRecordList records={bundle.clinicalRecords||[]} showPatient empty="No physician clinical records are available yet."/></Card>
    <Card><CardHeader title="Care observation" subtitle="Record something you observed while supporting this patient."/><form onSubmit={submitObservation} className="space-y-3"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Example: Patient felt dizzy after breakfast…" className="w-full rounded-xl border border-paper-300 p-3 text-sm outline-none focus:border-ink-700"/><button className="flex items-center gap-2 rounded-lg bg-ink-800 px-4 py-2 text-xs font-semibold text-white"><Send className="h-3.5 w-3.5"/>Share observation</button></form></Card>
    <EmergencyDialog open={emergencyDialogOpen} eyebrow="Connected patient" title={`Trigger emergency for ${p.name}?`} description={<>This will alert the HealthSync physician network and <strong>{p.name}'s connected caregivers</strong>.</>} note="HealthSync does not contact external emergency services." confirmLabel="Trigger Emergency" busyLabel="Sending SOS…" busy={sendingEmergency} onClose={()=>setEmergencyDialogOpen(false)} onConfirm={()=>void triggerEmergency()}/>
  </div>;
}
